# Build settings
name: BING-JE WU, Data Science Enthusiastic Learner
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# Where things are

highlighter: rouge

# resolve timezone issue when operating jekyll in local
timezone: Asia/Taipei